//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENBManager.Localization.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ENBManager.Localization.Strings.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active preset.
        /// </summary>
        public static string ACTIVE_PRESET {
            get {
                return ResourceManager.GetString("ACTIVE_PRESET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new preset.
        /// </summary>
        public static string ADD_NEW_PRESET {
            get {
                return ResourceManager.GetString("ADD_NEW_PRESET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An item with this this name already exists.
        /// </summary>
        public static string AN_ITEM_WITH_THIS_NAME_ALREADY_EXISTS {
            get {
                return ResourceManager.GetString("AN_ITEM_WITH_THIS_NAME_ALREADY_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appearance.
        /// </summary>
        public static string APPEARANCE {
            get {
                return ResourceManager.GetString("APPEARANCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application.
        /// </summary>
        public static string APPLICATION {
            get {
                return ResourceManager.GetString("APPLICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup.
        /// </summary>
        public static string BACKUP {
            get {
                return ResourceManager.GetString("BACKUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string BROWSE {
            get {
                return ResourceManager.GetString("BROWSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CANCEL {
            get {
                return ResourceManager.GetString("CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color scheme.
        /// </summary>
        public static string COLOR_SCHEME {
            get {
                return ResourceManager.GetString("COLOR_SCHEME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string CONTINUE {
            get {
                return ResourceManager.GetString("CONTINUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark mode.
        /// </summary>
        public static string DARK_MODE {
            get {
                return ResourceManager.GetString("DARK_MODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark mode shortcut.
        /// </summary>
        public static string DARK_MODE_SHORTCUT {
            get {
                return ResourceManager.GetString("DARK_MODE_SHORTCUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string DASHBOARD {
            get {
                return ResourceManager.GetString("DASHBOARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DELETE {
            get {
                return ResourceManager.GetString("DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagnostics.
        /// </summary>
        public static string DIAGNOSTICS {
            get {
                return ResourceManager.GetString("DIAGNOSTICS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty..
        /// </summary>
        public static string EMPTY {
            get {
                return ResourceManager.GetString("EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a new name:.
        /// </summary>
        public static string ENTER_A_NEW_NAME {
            get {
                return ResourceManager.GetString("ENTER_A_NEW_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Missing binaries.
        /// </summary>
        public static string ERROR_MISSING_BINARIES {
            get {
                return ResourceManager.GetString("ERROR_MISSING_BINARIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Preset could not be activated. Make sure the files included in the preset are compatible with the game directory.
        /// </summary>
        public static string ERROR_PRESET_COULD_NOT_BE_ACTIVATED {
            get {
                return ResourceManager.GetString("ERROR_PRESET_COULD_NOT_BE_ACTIVATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Unable to locate game directory.
        /// </summary>
        public static string ERROR_UNABLE_TO_LOCATE_GAME_DIRECTORY {
            get {
                return ResourceManager.GetString("ERROR_UNABLE_TO_LOCATE_GAME_DIRECTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files.
        /// </summary>
        public static string FILES {
            get {
                return ResourceManager.GetString("FILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game updated.
        /// </summary>
        public static string GAME_UPDATED {
            get {
                return ResourceManager.GetString("GAME_UPDATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Games.
        /// </summary>
        public static string GAMES {
            get {
                return ResourceManager.GetString("GAMES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string GENERAL {
            get {
                return ResourceManager.GetString("GENERAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to directory.
        /// </summary>
        public static string GO_TO_DIRECTORY {
            get {
                return ResourceManager.GetString("GO_TO_DIRECTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to ENBDev.
        /// </summary>
        public static string GO_TO_ENBDEV {
            get {
                return ResourceManager.GetString("GO_TO_ENBDEV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to Nexus Mods.
        /// </summary>
        public static string GO_TO_NEXUS_MODS {
            get {
                return ResourceManager.GetString("GO_TO_NEXUS_MODS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid.
        /// </summary>
        public static string GRID {
            get {
                return ResourceManager.GetString("GRID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed Games.
        /// </summary>
        public static string INSTALLED_GAMES {
            get {
                return ResourceManager.GetString("INSTALLED_GAMES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid name: The name may contain illegal characters.
        /// </summary>
        public static string INVALID_NAME {
            get {
                return ResourceManager.GetString("INVALID_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid preset: No eligible files were found.
        /// </summary>
        public static string INVALID_PRESET_NO_FILES {
            get {
                return ResourceManager.GetString("INVALID_PRESET_NO_FILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log level.
        /// </summary>
        public static string LOG_LEVEL {
            get {
                return ResourceManager.GetString("LOG_LEVEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage.
        /// </summary>
        public static string MANAGE {
            get {
                return ResourceManager.GetString("MANAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage binaries.
        /// </summary>
        public static string MANAGE_BINARIES {
            get {
                return ResourceManager.GetString("MANAGE_BINARIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If enabled, binary files will be automatically managed by the application. It is recommended to have this enabled.
        /// </summary>
        public static string MANAGE_BINARIES_TOOLTIP {
            get {
                return ResourceManager.GetString("MANAGE_BINARIES_TOOLTIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Misc.
        /// </summary>
        public static string MISC {
            get {
                return ResourceManager.GetString("MISC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string NO {
            get {
                return ResourceManager.GetString("NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No preset active.
        /// </summary>
        public static string NO_PRESET_ACTIVE {
            get {
                return ResourceManager.GetString("NO_PRESET_ACTIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No problems have been detected.
        /// </summary>
        public static string NO_PROBLEMS_HAVE_BEEN_DETECTED {
            get {
                return ResourceManager.GetString("NO_PROBLEMS_HAVE_BEEN_DETECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to activated..
        /// </summary>
        public static string PRESET_ACTIVATED {
            get {
                return ResourceManager.GetString("PRESET_ACTIVATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preset added.
        /// </summary>
        public static string PRESET_ADDED {
            get {
                return ResourceManager.GetString("PRESET_ADDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preset deleted.
        /// </summary>
        public static string PRESET_DELETED {
            get {
                return ResourceManager.GetString("PRESET_DELETED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preset updated.
        /// </summary>
        public static string PRESET_UPDATED {
            get {
                return ResourceManager.GetString("PRESET_UPDATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Presets.
        /// </summary>
        public static string PRESETS {
            get {
                return ResourceManager.GetString("PRESETS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        public static string RENAME {
            get {
                return ResourceManager.GetString("RENAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore.
        /// </summary>
        public static string RESTORE {
            get {
                return ResourceManager.GetString("RESTORE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SAVE {
            get {
                return ResourceManager.GetString("SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save current.
        /// </summary>
        public static string SAVE_CURRENT {
            get {
                return ResourceManager.GetString("SAVE_CURRENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXPERIMENTAL: Attempts to create a preset based on current ENB preset files in game directory.
        /// </summary>
        public static string SAVE_CURRENT_TOOLTIP_TEXT {
            get {
                return ResourceManager.GetString("SAVE_CURRENT_TOOLTIP_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a game in the menu to get started!.
        /// </summary>
        public static string SELECT_A_GAME_IN_THE_MENU_TO_GET_STARTED {
            get {
                return ResourceManager.GetString("SELECT_A_GAME_IN_THE_MENU_TO_GET_STARTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set root.
        /// </summary>
        public static string SET_ROOT {
            get {
                return ResourceManager.GetString("SET_ROOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets the selected folder as the top-level directory.
        /// </summary>
        public static string SET_ROOT_TOOLTIP_TEXT {
            get {
                return ResourceManager.GetString("SET_ROOT_TOOLTIP_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SETTINGS {
            get {
                return ResourceManager.GetString("SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start with last game active.
        /// </summary>
        public static string START_WITH_LAST_GAME_ACTIVE {
            get {
                return ResourceManager.GetString("START_WITH_LAST_GAME_ACTIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically selects the last active game upon startup.
        /// </summary>
        public static string START_WITH_LAST_GAME_ACTIVE_TOOLTIP {
            get {
                return ResourceManager.GetString("START_WITH_LAST_GAME_ACTIVE_TOOLTIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Themes &amp; Colors.
        /// </summary>
        public static string THEMES_AND_COLORS {
            get {
                return ResourceManager.GetString("THEMES_AND_COLORS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unmanaging a previously managed game will reset its content.
        /// </summary>
        public static string UNMANAGING_MANAGED_GAME {
            get {
                return ResourceManager.GetString("UNMANAGING_MANAGED_GAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string UPDATE {
            get {
                return ResourceManager.GetString("UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical list.
        /// </summary>
        public static string VERTICAL_LIST {
            get {
                return ResourceManager.GetString("VERTICAL_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View files.
        /// </summary>
        public static string VIEW_FILES {
            get {
                return ResourceManager.GetString("VIEW_FILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version mismatch: A newer binary version is currently used.
        /// </summary>
        public static string WARNING_A_NEWER_BINARY_VERSION_IS_CURRENTLY_USED {
            get {
                return ResourceManager.GetString("WARNING_A_NEWER_BINARY_VERSION_IS_CURRENTLY_USED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version mismatch: An older binary version is currently used.
        /// </summary>
        public static string WARNING_AN_OLDER_BINARY_VERSION_IS_CURRENTLY_USED {
            get {
                return ResourceManager.GetString("WARNING_AN_OLDER_BINARY_VERSION_IS_CURRENTLY_USED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: File(s) are missing from the active preset.
        /// </summary>
        public static string WARNING_FILES_ARE_MISSING_FROM_THE_ACTIVE_PRESET {
            get {
                return ResourceManager.GetString("WARNING_FILES_ARE_MISSING_FROM_THE_ACTIVE_PRESET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: Binaries have not yet been backed up.
        /// </summary>
        public static string WARNING_NO_BINARIES_BACKUP {
            get {
                return ResourceManager.GetString("WARNING_NO_BINARIES_BACKUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: The active preset differs from the preset currently used.
        /// </summary>
        public static string WARNING_THE_ACTIVE_PRESET_DIFFERS_FROM_THE_PRESET_CURRENTLY_USED {
            get {
                return ResourceManager.GetString("WARNING_THE_ACTIVE_PRESET_DIFFERS_FROM_THE_PRESET_CURRENTLY_USED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string YES {
            get {
                return ResourceManager.GetString("YES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are about to delete this item, are you sure?.
        /// </summary>
        public static string YOU_ARE_ABOUT_TO_DELETE_THIS_ITEM_ARE_YOU_SURE {
            get {
                return ResourceManager.GetString("YOU_ARE_ABOUT_TO_DELETE_THIS_ITEM_ARE_YOU_SURE", resourceCulture);
            }
        }
    }
}
